name: magic

on:
  issue_comment:
    types: [created]

jobs:
  something:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script:
            console.log(context)
